name: monitoring
services:
  grafana:
    container_name: grafana
    image: grafana/grafana-oss:latest
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - monitoring-network
    # ports:
    #   - 3000:3000
    restart: always

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    networks:
      - monitoring-network
    # ports:
    #   - 9090:9090
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg
    privileged: true
    networks:
      - monitoring-network
    # ports:
    #   - 8080:8080
    restart: always

  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node-exporter
    command:
      - "--path.rootfs=/host"
    network_mode: host
    pid: host
    restart: always
    volumes:
      - "/:/host:ro,rslave"
    # ports:
    #   - 9100:9100

networks:
  monitoring-network:

volumes:
  grafana-storage:
  prometheus-data:
